steps:
- name: "gcr.io/cloud-builders/docker"
  args:
  - build
  - "--tag=asia-northeast1-docker.pkg.dev/$PROJECT_ID/translator-for-slack/translator-for-slack"
  - .

images:
- "asia-northeast1-docker.pkg.dev/$PROJECT_ID/translator-for-slack/translator-for-slack"
